ExamCode/ExamCode.MVC/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace ExamCode.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ExamCode/ExamCode.MVC/Areas/Admin/Controllers/MemberController.cs
using ExamCode.BL.DTOs;
using ExamCode.BL.Exceptions;
using ExamCode.BL.Services.Abstractions;
using ExamCode.DAL.Models;
using ExamCode.MVC.HomeVMs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ExamCode.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MemberController : Controller
    {
        readonly IMemberService _memberService;

        

        public MemberController(IMemberService memberService)
        {
            _memberService = memberService;
        }

        public async Task<IActionResult> Index( int id)
        {
            ICollection<MemberListItemDto>  list = await _memberService.GetMemberListAsync();        
          
            return View(list);
        }


        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public  async Task<IActionResult> Create(int id)
        {
            try
            {
                await _memberService.CreateAsync(id);
                await _memberService.SaveChangeAsync();
                return RedirectToAction("Index");
            }
            catch(BaseException ex)
            {
                return BadRequest(ex.Message);  
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }


        public IActionResult Update()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(MemberUpdateDto memberUpdateDto)
        {
            try
            {
                await _memberService.UpdateAsync(memberUpdateDto);      
                await _memberService.SaveChangeAsync();
                return View("Index");

            }
            catch (BaseException ex)
            {
                return BadRequest (ex.Message);
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }

        public async Task<IActionResult> Details()
        {
            await _memberService.GetMemberViewItemsAsync();
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Delete(int id)
        {
            await _memberService.DeleteAsync(id);
            return RedirectToAction("Index");      
        }
    }
}

ExamCode/ExamCode.MVC/Areas/Admin/Controllers/PlanController.cs
using ExamCode.BL.DTOs;
using ExamCode.BL.Exceptions;
using ExamCode.BL.Services.Abstractions;
using ExamCode.BL.Services.Implementations;
using ExamCode.DAL.Models;
using Microsoft.AspNetCore.Mvc;

namespace ExamCode.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PlanController : Controller
    {
        readonly IPlanService _planService;

        public PlanController(IPlanService planService)
        {
            _planService = planService;
        }

        public async Task<IActionResult> Index(int id)
        {
            ICollection<PlanListItemDto> list = await _planService.GetPlanListAsync();  
            
            return View(list);
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id)
        {
            try
            {
                await _planService.CreateAsync(id);
                await _planService.SaveChangeAsync();
                return RedirectToAction("Index");
            }
            catch (BaseException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }

        public IActionResult Update()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(PlanUpdateDto planUpdateDto)
        {
            try
            {
                await _planService.UpdateAsync(planUpdateDto);
                await _planService.SaveChangeAsync();
                return View("Index");

            }
            catch (BaseException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }

        public async Task<IActionResult> Details()
        {
            await _planService.GetPlanViewItemsAsync();
            return View();
        }


        public async Task<IActionResult> Delete(int id)
        {
            await _planService.DeleteAsync(id);
            return RedirectToAction("Index");
        }

    }
}

ExamCode/ExamCode.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ExamCode.MVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ExamCode/ExamCode.MVC/Areas/Admin/Views/Member/Create.cshtml
@model MemberCreateDto

@{
    SelectList categories = ViewData["Plans"] as SelectList;
}

<form class="container" method="POST" enctype="multipart/form-data">
    <h2 class="my-4">Create </h2>
    <div class="mb-3">
        <label class="form-label" asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Position"></label>
        <input class="form-control" asp-for="Position" />
        <span class="text-danger" asp-validation-for="Position"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Image"></label>
        <input class="form-control" asp-for="Image" />
        <span class="text-danger" asp-validation-for="Image"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Surname"></label>
        <input class="form-control" asp-for="Surname" />
        <span class="text-danger" asp-validation-for="Surname"></span>
    </div>
  
        </select>
        <span class="text-danger" asp-validation-for="PlanId"></span>
    </div>
  
    <p class="text-danger text-center">@Html.ValidationMessage("CustomError")</p>
    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>

ExamCode/ExamCode.MVC/Areas/Admin/Views/Member/Details.cshtml
@model Member


<div class="container">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"> Details</h6>
        </div>
        <div class="card-body">
            <img style="width: 150px" src="~/uploads/places/@Model.ImageUrl" />
            <p>Id: @Model.Id</p>
            <p>Title: @Model.Name</p>
            <p>Description: @Model.Surname</p>
            <p>Minimum price: @Model.Position</p>
            <p>Create time: @Model.CreatedAt</p>
            @if (Model.UpdatedAt is not null)
            {
                <p>Update time: @Model.UpdatedAt</p>
            }
        </div>
    </div>
</div>}

ExamCode/ExamCode.MVC/Areas/Admin/Views/Member/Index.cshtml
@model ICollection<MemberListItemDto>

<!-- Begin Page Content -->
<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">MEMBER</h6>
        </div>
        <div class="d-flex justify-content-end px-3 mt-3">
            <a class="btn btn-primary" style="width: 160px" asp-controller="Place" asp-action="Create">+ Add</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Title</th>
                            <th>Category</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (MemberListItemDto item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>@item.Surname</td>
                                <td>@item.Position</td>
                                <td>
                                    <a class="btn btn-primary" asp-controller="Member" asp-action="Update" asp-route-id="@item.Id">Update</a>
                                    <a class="btn btn-danger" asp-controller="Member" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                    <a class="btn btn-info" asp-controller="Member" asp-action="Details" asp-route-id="@item.Id">Details</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
<!-- Page level plugins -->
<script src="~/admin/vendor/datatables/jquery.dataTables.min.js" defer></script>
<script src="~/admin/vendor/datatables/dataTables.bootstrap4.min.js" defer></script>

<!-- Page level custom scripts -->
<script src="~/admin/js/demo/datatables-demo.js" defer></script>

ExamCode/ExamCode.MVC/Areas/Admin/Views/Member/Update.cshtml
@model MemberUpdateDto
@{
    SelectList categories = ViewData["Plans"] as SelectList;
}

<form class="container" method="POST" enctype="multipart/form-data">
    <h2 class="my-4">Update </h2>
    <div class="mb-3">
        <label class="form-label" asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Position"></label>
        <input class="form-control" asp-for="Position" />
        <span class="text-danger" asp-validation-for="Position"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Image"></label>
        <input class="form-control" asp-for="Image" />
        <span class="text-danger" asp-validation-for="Image"></span>
    </div>
 
    <div class="mb-3">
        <label class="form-label" asp-for="Surname"></label>
        <input class="form-control" asp-for="Surname" />
        <span class="text-danger" asp-validation-for="Surname"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Position"></label>
        <input class="form-control" asp-for="Position" />
        <span class="text-danger" asp-validation-for="Position"></span>
    </div>

   
    <p class="text-danger text-center">@Html.ValidationMessage("CustomError")</p>
    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>

ExamCode/ExamCode.MVC/Areas/Admin/Views/Plan/Create.cshtml
@model PlanCreateDto


<form class="container" method="POST" enctype="multipart/form-data">
    <h2 class="my-4">Create </h2>
    <div class="mb-3">
        <label class="form-label" asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Description"></label>
        <input class="form-control" asp-for="Description" />
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Price"></label>
        <input class="form-control" asp-for="Price" />
        <span class="text-danger" asp-validation-for="Price"></span>
    </div>



    <p class="text-danger text-center">@Html.ValidationMessage("CustomError")</p>
    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>

ExamCode/ExamCode.MVC/Areas/Admin/Views/Plan/Details.cshtml
@model Plan


<div class="container">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"> Details</h6>
        </div>
        <div class="card-body">
           
            <p>Id: @Model.Id</p>
            <p>Title: @Model.Name</p>
            <p>Description: @Model.Description</p>
            <p>Minimum price: @Model.Price</p>
            <p>Create time: @Model.CreatedAt</p>
            @if (Model.UpdatedAt is not null)
            {
                <p>Update time: @Model.UpdatedAt</p>
            }
        </div>
    </div>
</div>}

ExamCode/ExamCode.MVC/Areas/Admin/Views/Plan/Index.cshtml
@model ICollection<PlanListItemDto>

<!-- Begin Page Content -->
<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Place</h6>
        </div>
        <div class="d-flex justify-content-end px-3 mt-3">
            <a class="btn btn-primary" style="width: 160px" asp-controller="Plan" asp-action="Create">+ Add</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Title</th>
                            <th>Category</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (PlanListItemDto item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>@item.Description</td>
                                <td>
                                    <a class="btn btn-primary" asp-controller="Plan" asp-action="Update" asp-route-id="@item.Id">Update</a>
                                    <a class="btn btn-danger" asp-controller="Plan" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                    <a class="btn btn-info" asp-controller="Plan" asp-action="Details" asp-route-id="@item.Id">Details</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
<!-- Page level plugins -->
<script src="~/admin/vendor/datatables/jquery.dataTables.min.js" defer></script>
<script src="~/admin/vendor/datatables/dataTables.bootstrap4.min.js" defer></script>

<!-- Page level custom scripts -->
<script src="~/admin/js/demo/datatables-demo.js" defer></script>

ExamCode/ExamCode.MVC/Areas/Admin/Views/Plan/Update.cshtml
@model PlanUpdateDto


<form class="container" method="POST" enctype="multipart/form-data">
    <h2 class="my-4">Update </h2>
    <div class="mb-3">
        <label class="form-label" asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Description"></label>
        <input class="form-control" asp-for="Description" />
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Price"></label>
        <input class="form-control" asp-for="Price" />
        <span class="text-danger" asp-validation-for="Price"></span>
    </div>



    <p class="text-danger text-center">@Html.ValidationMessage("CustomError")</p>
    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>

ExamCode/ExamCode.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>GreenHost - Web Hosting HTML Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="~/assets/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Open+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/assets/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/assets/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/assets/css/style.css" rel="stylesheet">
</head>

<body>
    <div class="container-xxl bg-white p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Navbar & Hero Start -->
        <div class="container-xxl position-relative p-0">
            <nav class="navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0">
                <a href="" class="navbar-brand p-0">
                    <h1 class="m-0"><i class="fa fa-server me-3"></i>GreenHost</h1>
                    <!-- <img src="img/logo.png" alt="Logo"> -->
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto py-0">
                        <a href="index.html" class="nav-item nav-link active">Home</a>
                        <a href="about.html" class="nav-item nav-link">About</a>
                        <a href="domain.html" class="nav-item nav-link">Domain</a>
                        <a href="hosting.html" class="nav-item nav-link">Hosting</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                            <div class="dropdown-menu m-0">
                                <a href="team.html" class="dropdown-item">Our Team</a>
                                <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                                <a href="comparison.html" class="dropdown-item">Comparison</a>
                            </div>
                        </div>
                        <a href="contact.html" class="nav-item nav-link">Contact</a>
                    </div>
                    <butaton type="button" class="btn text-secondary ms-3" data-bs-toggle="modal" data-bs-target="#searchModal"><i class="fa fa-search"></i></butaton>
                    <a href="" class="btn btn-secondary py-2 px-4 ms-3">Register</a>
                </div>
            </nav>

            <div class="container-xxl py-5 bg-primary hero-header mb-5">
                <div class="container my-5 py-5 px-lg-5">
                    <div class="row g-5">
                        <div class="col-lg-6 pt-5 text-center text-lg-start">
                            <h1 class="display-4 text-white mb-4 animated slideInLeft">Shared Hosting</h1>
                            <p class="text-white animated slideInLeft">Tempor rebum no at dolore lorem clita rebum rebum ipsum rebum stet dolor sed justo kasd.</p>
                            <h1 class="text-white mb-4 animated slideInLeft">
                                <small class="align-top fw-normal" style="font-size: 15px; line-height: 25px;">Starting:</small>
                                <span>$2.49</span>
                                <small class="align-bottom fw-normal" style="font-size: 15px; line-height: 33px;">/ Mo</small>
                            </h1>
                            <a href="" class="btn btn-secondary py-sm-3 px-sm-5 me-3 animated slideInLeft">Get Started Now</a>
                        </div>
                        <div class="col-lg-6 text-center text-lg-start">
                            <img class="img-fluid animated zoomIn" src="img/hero.png" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Navbar & Hero End -->
            @RenderBody()
        <!-- Footer Start -->
        <div class="container-fluid bg-primary text-white footer mt-5 pt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5 px-lg-5">
                <div class="row gy-5 gx-4 pt-5">
                    <div class="col-12">
                        <h5 class="fw-bold text-white mb-4">Subscribe Our Newsletter</h5>
                        <div class="position-relative" style="max-width: 400px;">
                            <input class="form-control bg-white border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="Enter your email">
                            <button type="button" class="btn btn-primary py-2 px-3 position-absolute top-0 end-0 mt-2 me-2">Submit</button>
                        </div>
                    </div>
                    <div class="col-lg-5 col-md-12">
                        <div class="row gy-5 g-4">
                            <div class="col-md-6">
                                <h5 class="fw-bold text-white mb-4">About Us</h5>
                                <a class="btn btn-link" href="">About Us</a>
                                <a class="btn btn-link" href="">Contact Us</a>
                                <a class="btn btn-link" href="">Privacy Policy</a>
                                <a class="btn btn-link" href="">Terms & Condition</a>
                                <a class="btn btn-link" href="">Support</a>
                            </div>
                            <div class="col-md-6">
                                <h5 class="fw-bold text-white mb-4">Our Services</h5>
                                <a class="btn btn-link" href="">Domain Register</a>
                                <a class="btn btn-link" href="">Shared Hosting</a>
                                <a class="btn btn-link" href="">VPS Hosting</a>
                                <a class="btn btn-link" href="">Dedicated Hosting</a>
                                <a class="btn btn-link" href="">Reseller Hosting</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3">
                        <h5 class="fw-bold text-white mb-4">Get In Touch</h5>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                        <div class="d-flex pt-2">
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-4 mt-lg-n5">
                        <div class="bg-light rounded" style="padding: 30px;">
                            <input type="text" class="form-control border-0 py-2 mb-2" placeholder="Name">
                            <input type="email" class="form-control border-0 py-2 mb-2" placeholder="Email">
                            <textarea class="form-control border-0 mb-2" rows="2" placeholder="Message"></textarea>
                            <button class="btn btn-primary w-100 py-2">Send Message</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container px-lg-5">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.

                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">
                                <a href="">Home</a>
                                <a href="">Cookies</a>
                                <a href="">Help</a>
                                <a href="">FQAs</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-secondary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/lib/wow/wow.min.js"></script>
    <script src="~/assets/lib/easing/easing.min.js"></script>
    <script src="~/assets/lib/waypoints/waypoints.min.js"></script>
    <script src="~/assets/lib/counterup/counterup.min.js"></script>
    <script src="~/assets/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/assets/js/main.js"></script>
</body>

</html>